name: Main

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [0.9.0, 0.10.0-beta.1, 0.10.0-beta.2, 0.10.0, 0.11.0-beta.1]

    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get update
    - run: sudo apt-get install -y datamash
    - run: ./bench.sh ${{ matrix.version }}
